### ISSUE TITLE
Bug Ship Placement 

### ISSUE THREAD

**Issue by 4E6F** [claudiu-sava/BattleShip#33]
wenn ich ein Schiff1 horizontal platziere und dann an der ecke des Schiffes ein vertikales Schiff2 platziere dann baut er mir ein schiff3 einfach so in die horizontale Richtung und verletzt die Bedingung das Schiff1 platz benötigt

**Comment by claudiu-sava** [comment]
This happnes because of a JS trigger. I replicated the bug, and a possible fix has been found.
